// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from internal/wire. DO NOT EDIT.
/* eslint-disable */

//////////
// source: wire.go
/*
Package wire defines the JSON DTOs exchanged with the web client. These Go
structs are the source of truth for the generated TypeScript types
(web/src/lib/api.gen.ts, produced by tygo — see tygo.yaml). Keep the JSON tags
stable; regenerate after changes (`make gen-ts`).
*/

/**
 * User is the safe public projection of an account.
 */
export interface User {
  id: string;
  username: string;
  role: string;
  must_change_password: boolean;
}
/**
 * LoginResponse is returned by POST /auth/login and GET /auth/me.
 */
export interface LoginResponse {
  user: User;
}
/**
 * Conversation is a chat/session summary.
 */
export interface Conversation {
  id: string;
  title: string;
  created_at: string;
  updated_at: string;
}
/**
 * ConversationList is the GET /conversations response.
 */
export interface ConversationList {
  conversations: Conversation[];
}
/**
 * Turn is one message in a conversation.
 */
export interface Turn {
  id: string;
  role: string;
  mode: string;
  text: string;
  created_at: string;
}
/**
 * TurnList is the GET /conversations/{id}/turns response.
 */
export interface TurnList {
  turns: Turn[];
}
/**
 * PostMessageResponse is returned when a streamed turn completes.
 */
export interface PostMessageResponse {
  user_turn_id: string;
  assistant_turn_id: string;
  text: string;
  interrupted: boolean;
}
/**
 * ConfigInfo is non-sensitive server info for the client header.
 */
export interface ConfigInfo {
  agent_name: string;
  llm_provider: string;
}
/**
 * AdminLLMInfo describes the active text backend (admin-only).
 */
export interface AdminLLMInfo {
  provider: string;
  model: string;
  base_url: string;
}
/**
 * RTCSessionStats is one live voice session's metrics for the admin view: app
 * counters plus Pion's network stats (loss/jitter/RTT). Mirrors
 * rtc.SessionStats; the realtime package stays decoupled from this wire format.
 */
export interface RTCSessionStats {
  session_id: string;
  user_id: string;
  conversation_id: string;
  mode: string;
  uptime_ms: number /* int64 */;
  rtp_packets_in: number /* uint64 */;
  decode_errors: number /* uint64 */;
  frames_out: number /* uint64 */;
  bytes_out: number /* uint64 */;
  frames_dropped: number /* uint64 */;
  interrupts: number /* uint64 */;
  played_ms: number /* int64 */;
  capture_ms: number /* int64 */;
  app_rtt_micros: number /* int64 */;
  packets_received: number /* uint32 */;
  packets_lost: number /* int32 */;
  jitter_seconds: number /* float64 */;
}
/**
 * RTCStats is the GET /admin/rtc response: every active live session.
 */
export interface RTCStats {
  sessions: RTCSessionStats[];
}
/**
 * AdminUser is a user row in the admin list.
 */
export interface AdminUser {
  id: string;
  username: string;
  role: string;
  status: string;
  must_change_password: boolean;
  created_at: string;
}
/**
 * AdminUserList is the GET /admin/users response.
 */
export interface AdminUserList {
  users: AdminUser[];
}
/**
 * ErrorResponse is the shape of all error bodies.
 */
export interface ErrorResponse {
  error: string;
}
