// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from internal/wire. DO NOT EDIT.
/* eslint-disable */

//////////
// source: wire.go
/*
Package wire defines the JSON DTOs exchanged with the web client. These Go
structs are the source of truth for the generated TypeScript types
(web/src/lib/api.gen.ts, produced by tygo — see tygo.yaml). Keep the JSON tags
stable; regenerate after changes (`make gen-ts`).
*/

/**
 * User is the safe public projection of an account.
 */
export interface User {
  id: string;
  username: string;
  role: string;
  must_change_password: boolean;
}
/**
 * LoginResponse is returned by POST /auth/login and GET /auth/me.
 */
export interface LoginResponse {
  user: User;
}
/**
 * Conversation is a chat/session summary.
 */
export interface Conversation {
  id: string;
  title: string;
  created_at: string;
  updated_at: string;
}
/**
 * ConversationList is the GET /conversations response.
 */
export interface ConversationList {
  conversations: Conversation[];
}
/**
 * Turn is one message in a conversation.
 */
export interface Turn {
  id: string;
  role: string;
  mode: string;
  text: string;
  created_at: string;
}
/**
 * TurnList is the GET /conversations/{id}/turns response.
 */
export interface TurnList {
  turns: Turn[];
}
/**
 * PostMessageResponse is returned when a streamed turn completes.
 */
export interface PostMessageResponse {
  user_turn_id: string;
  assistant_turn_id: string;
  text: string;
  interrupted: boolean;
}
/**
 * ConfigInfo is non-sensitive server info for the client header.
 */
export interface ConfigInfo {
  agent_name: string;
  llm_provider: string;
}
/**
 * AdminLLMInfo describes the active text backend (admin-only).
 */
export interface AdminLLMInfo {
  provider: string;
  model: string;
  base_url: string;
}
/**
 * RTCSessionStats is one live voice session's metrics for the admin view: app
 * counters plus Pion's network stats (loss/jitter/RTT). Mirrors
 * rtc.SessionStats; the realtime package stays decoupled from this wire format.
 */
export interface RTCSessionStats {
  session_id: string;
  user_id: string;
  conversation_id: string;
  mode: string;
  uptime_ms: number /* int64 */;
  rtp_packets_in: number /* uint64 */;
  decode_errors: number /* uint64 */;
  frames_out: number /* uint64 */;
  bytes_out: number /* uint64 */;
  frames_dropped: number /* uint64 */;
  interrupts: number /* uint64 */;
  dropped_turns: number /* uint64 */;
  played_ms: number /* int64 */;
  capture_ms: number /* int64 */;
  app_rtt_micros: number /* int64 */;
  packets_received: number /* uint32 */;
  packets_lost: number /* int32 */;
  jitter_seconds: number /* float64 */;
}
/**
 * RTCStats is the GET /admin/rtc response: every active live session.
 */
export interface RTCStats {
  sessions: RTCSessionStats[];
}
/**
 * AdminRuntime is the GET /admin/runtime response: local-inference backend status.
 */
export interface AdminRuntime {
  llm_provider: string;
  tts: TTSRuntime;
  asr: ASRRuntime;
  vad: VADRuntime;
}
/**
 * VADRuntime is the local Silero VAD engine + ONNX runtime status for the admin
 * view. The live conversation loop (Phase 6) needs this plus TTS + ASR available.
 */
export interface VADRuntime {
  enabled: boolean; // [voice] enabled
  available: boolean;
  loaded: boolean; // model currently resident (warm)
  reason?: string;
  runtime: ORTRuntime;
  cold_load_ms: number /* int64 */;
  probe_count: number /* int64 */;
  error_count: number /* int64 */;
  last_error?: string;
}
/**
 * ASRRuntime is the local streaming ASR (Nemotron) engine + ONNX runtime status
 * for the admin view.
 */
export interface ASRRuntime {
  enabled: boolean;
  available: boolean;
  loaded: boolean; // models currently resident (warm)
  language: string;
  biasing: boolean; // agent-name biasing active
  reason?: string;
  runtime: ORTRuntime;
  cold_load_ms: number /* int64 */; // last cold model-load latency
  last_chunk_ms: number /* int64 */; // last chunk decode latency
  chunk_count: number /* int64 */;
  error_count: number /* int64 */;
  last_error?: string;
}
/**
 * TTSRuntime is the local TTS engine + ONNX runtime status for the admin view.
 */
export interface TTSRuntime {
  enabled: boolean;
  available: boolean;
  loaded: boolean; // models currently resident (warm)
  voice: string;
  lang: string;
  steps: number /* int */;
  reason?: string; // why unavailable
  runtime: ORTRuntime;
  cold_load_ms: number /* int64 */; // last cold model-load latency
  last_synth_ms: number /* int64 */; // last per-sentence synth latency
  synth_count: number /* int64 */;
  error_count: number /* int64 */;
  last_error?: string;
}
/**
 * ORTRuntime is the ONNX Runtime library status (version/provider/lib path).
 */
export interface ORTRuntime {
  available: boolean;
  version?: string;
  provider?: string;
  lib_path?: string;
  reason?: string;
}
/**
 * AdminUser is a user row in the admin list.
 */
export interface AdminUser {
  id: string;
  username: string;
  role: string;
  status: string;
  must_change_password: boolean;
  created_at: string;
}
/**
 * AdminUserList is the GET /admin/users response.
 */
export interface AdminUserList {
  users: AdminUser[];
}
/**
 * SandboxEnvironment is a user's Sandbox Environment policy (GET/PUT
 * /sandbox/environment). AvailableTools is server-supplied (the built-in tool
 * set) so the UI can offer the full list; AllowedTools is the user's selection.
 */
export interface SandboxEnvironment {
  allowed_tools: string[];
  available_tools: string[];
  mcp_servers: SandboxMCPServer[];
  network: SandboxNetworkPolicy;
  writable_mounts: string[];
  secret_grants: SandboxSecretGrant[];
}
/**
 * SandboxMCPServer is a configured MCP server (name + url).
 */
export interface SandboxMCPServer {
  name: string;
  url: string;
}
/**
 * SandboxNetworkPolicy is the default posture plus the host:port allow-list.
 */
export interface SandboxNetworkPolicy {
  default: string; // deny | allow
  allow: SandboxNetworkRule[];
}
/**
 * SandboxNetworkRule is one host:port allow-list entry.
 */
export interface SandboxNetworkRule {
  host: string;
  port: number /* int */;
}
/**
 * SandboxSecretGrant binds a vaulted secret to its injected env-var name.
 */
export interface SandboxSecretGrant {
  secret_id: string;
  env_name: string;
}
/**
 * Secret is the non-sensitive metadata for a vaulted secret (never the value).
 */
export interface Secret {
  id: string;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
}
/**
 * SecretList is the GET /sandbox/secrets response.
 */
export interface SecretList {
  secrets: Secret[];
}
/**
 * AdminSandbox is the GET /admin/sandbox response: runtime status + usage.
 */
export interface AdminSandbox {
  runtime: SandboxRuntime;
  users: SandboxUserUsage[];
  runs: SandboxRunInfo[];
}
/**
 * SandboxRuntime is the sbx runner status for the admin view.
 */
export interface SandboxRuntime {
  enabled: boolean;
  available: boolean;
  version?: string;
  pinned: string;
  path?: string;
  approval: string;
  reason?: string;
}
/**
 * SandboxUserUsage is one user's sandbox storage + run footprint.
 */
export interface SandboxUserUsage {
  user_id: string;
  username: string;
  workspace_bytes: number /* int64 */;
  run_count: number /* int */;
}
/**
 * SandboxRunInfo is one audit-log row (no secret values; command is redacted).
 */
export interface SandboxRunInfo {
  id: string;
  user_id: string;
  conversation_id: string;
  tool: string;
  decision: string;
  exit_code: number /* int */;
  duration_ms: number /* int64 */;
  command: string;
  error: string;
  created_at: string;
}
/**
 * ErrorResponse is the shape of all error bodies.
 */
export interface ErrorResponse {
  error: string;
}
