// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from internal/wire. DO NOT EDIT.
/* eslint-disable */

//////////
// source: wire.go
/*
Package wire defines the JSON DTOs exchanged with the web client. These Go
structs are the source of truth for the generated TypeScript types
(web/src/lib/api.gen.ts, produced by tygo — see tygo.yaml). Keep the JSON tags
stable; regenerate after changes (`make gen-ts`).
*/

/**
 * User is the safe public projection of an account.
 */
export interface User {
  id: string;
  username: string;
  role: string;
  must_change_password: boolean;
}
/**
 * LoginResponse is returned by POST /auth/login and GET /auth/me.
 */
export interface LoginResponse {
  user: User;
}
/**
 * Conversation is a chat/session summary.
 */
export interface Conversation {
  id: string;
  title: string;
  created_at: string;
  updated_at: string;
}
/**
 * ConversationList is the GET /conversations response.
 */
export interface ConversationList {
  conversations: Conversation[];
}
/**
 * Turn is one message in a conversation.
 */
export interface Turn {
  id: string;
  role: string;
  mode: string;
  text: string;
  created_at: string;
}
/**
 * TurnList is the GET /conversations/{id}/turns response.
 */
export interface TurnList {
  turns: Turn[];
}
/**
 * PostMessageResponse is returned when a streamed turn completes.
 */
export interface PostMessageResponse {
  user_turn_id: string;
  assistant_turn_id: string;
  text: string;
  interrupted: boolean;
}
/**
 * ConfigInfo is non-sensitive server info for the client header.
 */
export interface ConfigInfo {
  agent_name: string;
  llm_provider: string;
}
/**
 * AdminLLMInfo describes the active text backend (admin-only).
 */
export interface AdminLLMInfo {
  provider: string;
  model: string;
  base_url: string;
}
/**
 * RTCSessionStats is one live voice session's metrics for the admin view: app
 * counters plus Pion's network stats (loss/jitter/RTT). Mirrors
 * rtc.SessionStats; the realtime package stays decoupled from this wire format.
 */
export interface RTCSessionStats {
  session_id: string;
  user_id: string;
  conversation_id: string;
  mode: string;
  uptime_ms: number /* int64 */;
  rtp_packets_in: number /* uint64 */;
  decode_errors: number /* uint64 */;
  frames_out: number /* uint64 */;
  bytes_out: number /* uint64 */;
  frames_dropped: number /* uint64 */;
  interrupts: number /* uint64 */;
  dropped_turns: number /* uint64 */;
  played_ms: number /* int64 */;
  capture_ms: number /* int64 */;
  app_rtt_micros: number /* int64 */;
  packets_received: number /* uint32 */;
  packets_lost: number /* int32 */;
  jitter_seconds: number /* float64 */;
}
/**
 * RTCStats is the GET /admin/rtc response: every active live session.
 */
export interface RTCStats {
  sessions: RTCSessionStats[];
}
/**
 * AdminRuntime is the GET /admin/runtime response: local-inference backend status.
 */
export interface AdminRuntime {
  llm_provider: string;
  tts: TTSRuntime;
  asr: ASRRuntime;
  vad: VADRuntime;
}
/**
 * VADRuntime is the local Silero VAD engine + ONNX runtime status for the admin
 * view. The live conversation loop (Phase 6) needs this plus TTS + ASR available.
 */
export interface VADRuntime {
  enabled: boolean; // [voice] enabled
  available: boolean;
  loaded: boolean; // model currently resident (warm)
  reason?: string;
  runtime: ORTRuntime;
  cold_load_ms: number /* int64 */;
  probe_count: number /* int64 */;
  error_count: number /* int64 */;
  last_error?: string;
}
/**
 * ASRRuntime is the local streaming ASR (Nemotron) engine + ONNX runtime status
 * for the admin view.
 */
export interface ASRRuntime {
  enabled: boolean;
  available: boolean;
  loaded: boolean; // models currently resident (warm)
  language: string;
  biasing: boolean; // agent-name biasing active
  reason?: string;
  runtime: ORTRuntime;
  cold_load_ms: number /* int64 */; // last cold model-load latency
  last_chunk_ms: number /* int64 */; // last chunk decode latency
  chunk_count: number /* int64 */;
  error_count: number /* int64 */;
  last_error?: string;
}
/**
 * TTSRuntime is the local TTS engine + ONNX runtime status for the admin view.
 */
export interface TTSRuntime {
  enabled: boolean;
  available: boolean;
  loaded: boolean; // models currently resident (warm)
  voice: string;
  lang: string;
  steps: number /* int */;
  reason?: string; // why unavailable
  runtime: ORTRuntime;
  cold_load_ms: number /* int64 */; // last cold model-load latency
  last_synth_ms: number /* int64 */; // last per-sentence synth latency
  synth_count: number /* int64 */;
  error_count: number /* int64 */;
  last_error?: string;
}
/**
 * ORTRuntime is the ONNX Runtime library status (version/provider/lib path).
 */
export interface ORTRuntime {
  available: boolean;
  version?: string;
  provider?: string;
  lib_path?: string;
  reason?: string;
}
/**
 * AdminUser is a user row in the admin list.
 */
export interface AdminUser {
  id: string;
  username: string;
  role: string;
  status: string;
  must_change_password: boolean;
  created_at: string;
}
/**
 * AdminUserList is the GET /admin/users response.
 */
export interface AdminUserList {
  users: AdminUser[];
}
/**
 * SandboxEnvironment is a user's Sandbox Environment policy (GET/PUT
 * /sandbox/environment). AvailableTools is server-supplied (the built-in tool
 * set) so the UI can offer the full list; AllowedTools is the user's selection.
 */
export interface SandboxEnvironment {
  allowed_tools: string[];
  available_tools: string[];
  mcp_servers: SandboxMCPServer[];
  network: SandboxNetworkPolicy;
  writable_mounts: string[];
  secret_grants: SandboxSecretGrant[];
}
/**
 * SandboxMCPServer is a configured MCP server (name + url).
 */
export interface SandboxMCPServer {
  name: string;
  url: string;
}
/**
 * SandboxNetworkPolicy is the default posture plus the host:port allow-list.
 */
export interface SandboxNetworkPolicy {
  default: string; // deny | allow
  allow: SandboxNetworkRule[];
}
/**
 * SandboxNetworkRule is one host:port allow-list entry.
 */
export interface SandboxNetworkRule {
  host: string;
  port: number /* int */;
}
/**
 * SandboxSecretGrant binds a vaulted secret to its injected env-var name.
 */
export interface SandboxSecretGrant {
  secret_id: string;
  env_name: string;
}
/**
 * Secret is the non-sensitive metadata for a vaulted secret (never the value).
 */
export interface Secret {
  id: string;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
}
/**
 * SecretList is the GET /sandbox/secrets response.
 */
export interface SecretList {
  secrets: Secret[];
}
/**
 * AdminSandbox is the GET /admin/sandbox response: runtime status + usage.
 */
export interface AdminSandbox {
  runtime: SandboxRuntime;
  users: SandboxUserUsage[];
  runs: SandboxRunInfo[];
}
/**
 * SandboxRuntime is the sbx runner status for the admin view.
 */
export interface SandboxRuntime {
  enabled: boolean;
  available: boolean;
  version?: string;
  pinned: string;
  path?: string;
  approval: string;
  reason?: string;
}
/**
 * SandboxUserUsage is one user's sandbox storage + run footprint.
 */
export interface SandboxUserUsage {
  user_id: string;
  username: string;
  workspace_bytes: number /* int64 */;
  run_count: number /* int */;
}
/**
 * SandboxRunInfo is one audit-log row (no secret values; command is redacted).
 */
export interface SandboxRunInfo {
  id: string;
  user_id: string;
  conversation_id: string;
  tool: string;
  decision: string;
  exit_code: number /* int */;
  duration_ms: number /* int64 */;
  command: string;
  error: string;
  created_at: string;
}
/**
 * AgentInfo is one callable coding-agent's catalog entry for a user: its static
 * capability plus that user's profile state and current eligibility to run. It
 * never carries a credential — only the auth-profile TYPE.
 */
export interface AgentInfo {
  provider: string;
  display_name: string;
  auth_types: string[]; // profile types the user may configure
  browser_auth: boolean; // supports interactive login
  local_only: boolean; // Pi
  tool_name: string; // routable tool, e.g. "agent.codex.run"
  configured: boolean; // a profile exists
  configured_auth_type?: string;
  status?: string; // profile status (authenticated/...)
  runnable: boolean; // eligible to be called right now
  reason?: string; // why not runnable / not configurable
}
/**
 * AgentCatalog is the GET /agents response: the per-user agent list + the
 * server-level gates that decide eligibility.
 */
export interface AgentCatalog {
  enabled: boolean; // [sandbox] tool execution on
  browser_auth_available: boolean; // interactive login usable (sbx present)
  network_isolated: boolean; // operator asserted controlled egress
  agents: AgentInfo[];
}
/**
 * SetAgentKey is the POST /agents/{provider}/key body (configure an API-key/token
 * profile). The value is write-only — never returned.
 */
export interface SetAgentKey {
  auth_type: string; // api_key | oauth_token
  value: string;
}
/**
 * StartAgentLogin is the POST /agents/{provider}/login body.
 */
export interface StartAgentLogin {
  device_auth: boolean; // use the device/paste-code flow
}
/**
 * AgentLoginStarted is the POST /agents/{provider}/login response.
 */
export interface AgentLoginStarted {
  session_id: string;
}
/**
 * AgentLoginInput is the POST /agents/login/{id}/input body (a pasted code/line).
 */
export interface AgentLoginInput {
  data: string;
}
/**
 * AgentLoginHint is an actionable item detected in login output (URL/code/prompt).
 */
export interface AgentLoginHint {
  kind: string;
  value: string;
}
/**
 * AgentLoginFrame is one streamed login event over the login SSE channel. It never
 * carries a persisted credential — only the transient live view.
 */
export interface AgentLoginFrame {
  type: string; // output | hint | done
  text?: string;
  hint?: AgentLoginHint;
  ok?: boolean;
  error?: string;
}
/**
 * AdminAgentProfile is one user's coarse agent-profile status for the admin view —
 * never a token/URL/code.
 */
export interface AdminAgentProfile {
  user_id: string;
  username: string;
  provider: string;
  auth_type: string;
  status: string;
  updated_at: string;
}
/**
 * AdminAgents is the GET /admin/agents response.
 */
export interface AdminAgents {
  available: boolean;
  browser_auth_available: boolean;
  reason?: string;
  profiles: AdminAgentProfile[];
}
/**
 * AutomationSummary is a list-row projection of an automation (no full definition).
 */
export interface AutomationSummary {
  id: string;
  name: string;
  enabled: boolean;
  trigger: string; // interval | cron | manual
  next_run?: string;
  last_run?: string;
  last_status?: string;
  created_at: string;
  updated_at: string;
}
/**
 * AutomationList is the GET /automations response.
 */
export interface AutomationList {
  automations: AutomationSummary[];
}
/**
 * AutomationDetail is one automation with its full automation.v1 document.
 */
export interface AutomationDetail {
  id: string;
  name: string;
  enabled: boolean;
  trigger: string;
  next_run?: string;
  last_run?: string;
  last_status?: string;
  created_at: string;
  updated_at: string;
  definition: unknown;
}
/**
 * AutomationInput is the create/update/import body: the automation.v1 document.
 */
export interface AutomationInput {
  definition: unknown;
}
/**
 * AutomationIssue is one structural or eligibility problem (path-tagged for repair).
 */
export interface AutomationIssue {
  path: string;
  message: string;
}
/**
 * AutomationValidation reports structural validity AND enable-eligibility separately,
 * so the builder can show "valid but not yet runnable" (missing secret/agent) clearly.
 */
export interface AutomationValidation {
  valid: boolean;
  issues?: AutomationIssue[];
  eligible: boolean;
  eligibility_issues?: AutomationIssue[];
}
/**
 * SetAutomationEnabled is the POST /automations/{id}/enabled body.
 */
export interface SetAutomationEnabled {
  enabled: boolean;
}
/**
 * TriggerAutomationResponse is the POST /automations/{id}/run response.
 */
export interface TriggerAutomationResponse {
  run_id: string;
}
/**
 * AutomationRunSummary is a run-history row (no full record).
 */
export interface AutomationRunSummary {
  id: string;
  automation_id: string;
  status: string;
  trigger: string;
  error?: string;
  started_at?: string;
  finished_at?: string;
  duration_ms: number /* int64 */;
}
/**
 * AutomationRunList is the GET /automations/{id}/runs response.
 */
export interface AutomationRunList {
  runs: AutomationRunSummary[];
}
/**
 * AutomationRunDetail is one run with its full immutable record + artifact metadata.
 */
export interface AutomationRunDetail {
  id: string;
  automation_id: string;
  status: string;
  trigger: string;
  error?: string;
  started_at?: string;
  finished_at?: string;
  duration_ms: number /* int64 */;
  record: unknown;
  artifacts: AutomationArtifactInfo[];
}
/**
 * AutomationArtifactInfo is one promoted artifact's metadata (content via download).
 */
export interface AutomationArtifactInfo {
  id: string;
  name: string;
  step_id: string;
  size: number /* int64 */;
  created_at: string;
}
/**
 * AutomationAgentOption is one callable agent's availability for the builder.
 */
export interface AutomationAgentOption {
  provider: string;
  configured: boolean;
  runnable: boolean;
}
/**
 * AutomationMeta is the GET /automations/meta catalog the builder UI renders against:
 * the closed tool/adapter/host-service sets plus this owner's secrets + agent
 * availability and the server gates that decide eligibility.
 */
export interface AutomationMeta {
  enabled: boolean; // [automations] on
  available: boolean; // scheduler + sandbox usable
  reason?: string; // why unavailable
  schema_version: string;
  tools: string[];
  adapters: string[];
  host_services: string[];
  secrets: string[];
  agents: AutomationAgentOption[];
  network_isolated: boolean;
  agents_enabled: boolean;
}
/**
 * AssistAutomationRequest asks the active LLM to draft an automation.v1 document from
 * a natural-language description.
 */
export interface AssistAutomationRequest {
  prompt: string;
}
/**
 * AssistAutomationResponse returns the LLM-drafted, schema-validated definition (for
 * human review before enabling), the validation outcome, and how many attempts the
 * retry loop took.
 */
export interface AssistAutomationResponse {
  definition: unknown; // always valid JSON ("null" if unparseable)
  raw_text?: string;
  valid: boolean;
  issues?: AutomationIssue[];
  attempts: number /* int */;
}
/**
 * ErrorResponse is the shape of all error bodies.
 */
export interface ErrorResponse {
  error: string;
}
