// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from internal/events. DO NOT EDIT.
/* eslint-disable */

//////////
// source: events.go
/*
Package events defines Hina's typed event envelope and an in-process pub/sub
bus. The same envelope is delivered over the user/admin SSE streams now and
over the WebRTC RTCDataChannel in the voice phases, so the wire shape is fixed
here once. The events table is the durable source of truth behind replay.
*/

/**
 * Source identifies where an event originated.
 */
export const SourceClient = "client";
/**
 * Source identifies where an event originated.
 */
export const SourceServer = "server";
/**
 * Source identifies where an event originated.
 */
export const SourceRuntime = "runtime";
/**
 * Source identifies where an event originated.
 */
export const SourceSandbox = "sandbox";
/**
 * Source identifies where an event originated.
 */
export const SourceOpenAIRealtime = "openai_realtime";
/**
 * Core lifecycle event types implemented in Phase 1. The audio/tool/automation
 * types from the plan are added in their phases but share this envelope.
 */
export const TypeSessionCreated = "SessionCreated";
/**
 * Core lifecycle event types implemented in Phase 1. The audio/tool/automation
 * types from the plan are added in their phases but share this envelope.
 */
export const TypeSessionResumed = "SessionResumed";
/**
 * Core lifecycle event types implemented in Phase 1. The audio/tool/automation
 * types from the plan are added in their phases but share this envelope.
 */
export const TypeUserTextSubmitted = "UserTextSubmitted";
/**
 * Core lifecycle event types implemented in Phase 1. The audio/tool/automation
 * types from the plan are added in their phases but share this envelope.
 */
export const TypeTurnStarted = "TurnStarted";
/**
 * Core lifecycle event types implemented in Phase 1. The audio/tool/automation
 * types from the plan are added in their phases but share this envelope.
 */
export const TypeTurnCommitted = "TurnCommitted";
/**
 * Core lifecycle event types implemented in Phase 1. The audio/tool/automation
 * types from the plan are added in their phases but share this envelope.
 */
export const TypeAgentTextDelta = "AgentTextDelta";
/**
 * Core lifecycle event types implemented in Phase 1. The audio/tool/automation
 * types from the plan are added in their phases but share this envelope.
 */
export const TypeAgentTextCompleted = "AgentTextCompleted";
/**
 * Core lifecycle event types implemented in Phase 1. The audio/tool/automation
 * types from the plan are added in their phases but share this envelope.
 */
export const TypeError = "ErrorEvent";
/**
 * Event is the typed envelope. JSON field names are the wire contract; note
 * ConversationID serializes as "session_id" (the product-level "session").
 */
export interface Event {
  event_id: string;
  session_id?: string;
  user_id?: string;
  turn_id?: string;
  seq: number /* int64 */;
  server_ts: string;
  source: string;
  type: string;
  payload?: unknown;
}
