// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from internal/events. DO NOT EDIT.
/* eslint-disable */

//////////
// source: events.go
/*
Package events defines Hina's typed event envelope and an in-process pub/sub
bus. The same envelope is delivered over the user/admin SSE streams now and
over the WebRTC RTCDataChannel in the voice phases, so the wire shape is fixed
here once. The events table is the durable source of truth behind replay.
*/

/**
 * Source identifies where an event originated.
 */
export const SourceClient = "client";
/**
 * Source identifies where an event originated.
 */
export const SourceServer = "server";
/**
 * Source identifies where an event originated.
 */
export const SourceRuntime = "runtime";
/**
 * Source identifies where an event originated.
 */
export const SourceSandbox = "sandbox";
/**
 * Source identifies where an event originated.
 */
export const SourceOpenAIRealtime = "openai_realtime";
/**
 * Core lifecycle event types implemented in Phase 1. The audio/tool/automation
 * types from the plan are added in their phases but share this envelope.
 */
export const TypeSessionCreated = "SessionCreated";
/**
 * Core lifecycle event types implemented in Phase 1. The audio/tool/automation
 * types from the plan are added in their phases but share this envelope.
 */
export const TypeSessionResumed = "SessionResumed";
/**
 * Core lifecycle event types implemented in Phase 1. The audio/tool/automation
 * types from the plan are added in their phases but share this envelope.
 */
export const TypeUserTextSubmitted = "UserTextSubmitted";
/**
 * Core lifecycle event types implemented in Phase 1. The audio/tool/automation
 * types from the plan are added in their phases but share this envelope.
 */
export const TypeTurnStarted = "TurnStarted";
/**
 * Core lifecycle event types implemented in Phase 1. The audio/tool/automation
 * types from the plan are added in their phases but share this envelope.
 */
export const TypeTurnCommitted = "TurnCommitted";
/**
 * Core lifecycle event types implemented in Phase 1. The audio/tool/automation
 * types from the plan are added in their phases but share this envelope.
 */
export const TypeAgentTextDelta = "AgentTextDelta";
/**
 * Core lifecycle event types implemented in Phase 1. The audio/tool/automation
 * types from the plan are added in their phases but share this envelope.
 */
export const TypeAgentTextCompleted = "AgentTextCompleted";
/**
 * Core lifecycle event types implemented in Phase 1. The audio/tool/automation
 * types from the plan are added in their phases but share this envelope.
 */
export const TypeError = "ErrorEvent";
/**
 * Phase 3 audio/live event types. They share the same envelope and flow over
 * both the SSE stream (admin/owner observability) and the WebRTC events
 * datachannel (the live client). In Phase 3 they are delivered live-only
 * (ephemeral, seq==0) — transport proof, not durable transcript; the durable
 * voice-turn record lands in Phase 6. ModeChanged doubles as the client→server
 * control to select the outbound source (loopback|tone|idle) and the
 * server→client acknowledgement.
 */
export const TypeModeChanged = "ModeChanged";
/**
 * Phase 3 audio/live event types. They share the same envelope and flow over
 * both the SSE stream (admin/owner observability) and the WebRTC events
 * datachannel (the live client). In Phase 3 they are delivered live-only
 * (ephemeral, seq==0) — transport proof, not durable transcript; the durable
 * voice-turn record lands in Phase 6. ModeChanged doubles as the client→server
 * control to select the outbound source (loopback|tone|idle) and the
 * server→client acknowledgement.
 */
export const TypeAudioInputFrame = "AudioInputFrame";
/**
 * Phase 3 audio/live event types. They share the same envelope and flow over
 * both the SSE stream (admin/owner observability) and the WebRTC events
 * datachannel (the live client). In Phase 3 they are delivered live-only
 * (ephemeral, seq==0) — transport proof, not durable transcript; the durable
 * voice-turn record lands in Phase 6. ModeChanged doubles as the client→server
 * control to select the outbound source (loopback|tone|idle) and the
 * server→client acknowledgement.
 */
export const TypeAudioOutputFrame = "AudioOutputFrame";
/**
 * Phase 3 audio/live event types. They share the same envelope and flow over
 * both the SSE stream (admin/owner observability) and the WebRTC events
 * datachannel (the live client). In Phase 3 they are delivered live-only
 * (ephemeral, seq==0) — transport proof, not durable transcript; the durable
 * voice-turn record lands in Phase 6. ModeChanged doubles as the client→server
 * control to select the outbound source (loopback|tone|idle) and the
 * server→client acknowledgement.
 */
export const TypePlaybackStarted = "PlaybackStarted";
/**
 * Phase 3 audio/live event types. They share the same envelope and flow over
 * both the SSE stream (admin/owner observability) and the WebRTC events
 * datachannel (the live client). In Phase 3 they are delivered live-only
 * (ephemeral, seq==0) — transport proof, not durable transcript; the durable
 * voice-turn record lands in Phase 6. ModeChanged doubles as the client→server
 * control to select the outbound source (loopback|tone|idle) and the
 * server→client acknowledgement.
 */
export const TypePlaybackProgress = "PlaybackProgress";
/**
 * Phase 3 audio/live event types. They share the same envelope and flow over
 * both the SSE stream (admin/owner observability) and the WebRTC events
 * datachannel (the live client). In Phase 3 they are delivered live-only
 * (ephemeral, seq==0) — transport proof, not durable transcript; the durable
 * voice-turn record lands in Phase 6. ModeChanged doubles as the client→server
 * control to select the outbound source (loopback|tone|idle) and the
 * server→client acknowledgement.
 */
export const TypePlaybackStopped = "PlaybackStopped";
/**
 * Phase 3 audio/live event types. They share the same envelope and flow over
 * both the SSE stream (admin/owner observability) and the WebRTC events
 * datachannel (the live client). In Phase 3 they are delivered live-only
 * (ephemeral, seq==0) — transport proof, not durable transcript; the durable
 * voice-turn record lands in Phase 6. ModeChanged doubles as the client→server
 * control to select the outbound source (loopback|tone|idle) and the
 * server→client acknowledgement.
 */
export const TypeUserInterrupted = "UserInterrupted";
/**
 * Phase 4 local-TTS event types. TTSStarted/TTSCompleted bracket a spoken reply
 * (per conversation, alongside PlaybackStarted/Stopped on the audio path). The
 * RuntimeModel* types report the shared ONNX runtime's lazy-load / idle-unload
 * lifecycle and load failures — global (no conversation), for admin
 * observability of the local-inference backend.
 */
export const TypeSpeakText = "SpeakText"; // client->server: speak this text into the live session
/**
 * Phase 4 local-TTS event types. TTSStarted/TTSCompleted bracket a spoken reply
 * (per conversation, alongside PlaybackStarted/Stopped on the audio path). The
 * RuntimeModel* types report the shared ONNX runtime's lazy-load / idle-unload
 * lifecycle and load failures — global (no conversation), for admin
 * observability of the local-inference backend.
 */
export const TypeTTSStarted = "TTSStarted";
/**
 * Phase 4 local-TTS event types. TTSStarted/TTSCompleted bracket a spoken reply
 * (per conversation, alongside PlaybackStarted/Stopped on the audio path). The
 * RuntimeModel* types report the shared ONNX runtime's lazy-load / idle-unload
 * lifecycle and load failures — global (no conversation), for admin
 * observability of the local-inference backend.
 */
export const TypeTTSCompleted = "TTSCompleted";
/**
 * Phase 4 local-TTS event types. TTSStarted/TTSCompleted bracket a spoken reply
 * (per conversation, alongside PlaybackStarted/Stopped on the audio path). The
 * RuntimeModel* types report the shared ONNX runtime's lazy-load / idle-unload
 * lifecycle and load failures — global (no conversation), for admin
 * observability of the local-inference backend.
 */
export const TypeRuntimeModelLoaded = "RuntimeModelLoaded";
/**
 * Phase 4 local-TTS event types. TTSStarted/TTSCompleted bracket a spoken reply
 * (per conversation, alongside PlaybackStarted/Stopped on the audio path). The
 * RuntimeModel* types report the shared ONNX runtime's lazy-load / idle-unload
 * lifecycle and load failures — global (no conversation), for admin
 * observability of the local-inference backend.
 */
export const TypeRuntimeModelUnloaded = "RuntimeModelUnloaded";
/**
 * Phase 4 local-TTS event types. TTSStarted/TTSCompleted bracket a spoken reply
 * (per conversation, alongside PlaybackStarted/Stopped on the audio path). The
 * RuntimeModel* types report the shared ONNX runtime's lazy-load / idle-unload
 * lifecycle and load failures — global (no conversation), for admin
 * observability of the local-inference backend.
 */
export const TypeRuntimeModelError = "RuntimeModelError";
/**
 * Phase 5 local-ASR event types. ListenStarted/ListenStopped are the
 * client→server controls that delimit a speech segment (turn boundaries are
 * Phase 6's VAD; here the client marks them). While listening, the server emits
 * ASRPartial per decoded chunk and one ASRFinal on the segment commit, carrying
 * the wake-detection result + the address-stripped request body.
 */
export const TypeListenStarted = "ListenStarted"; // client->server: begin feeding mic audio to ASR
/**
 * Phase 5 local-ASR event types. ListenStarted/ListenStopped are the
 * client→server controls that delimit a speech segment (turn boundaries are
 * Phase 6's VAD; here the client marks them). While listening, the server emits
 * ASRPartial per decoded chunk and one ASRFinal on the segment commit, carrying
 * the wake-detection result + the address-stripped request body.
 */
export const TypeListenStopped = "ListenStopped"; // client->server: commit the segment -> ASRFinal
/**
 * Phase 5 local-ASR event types. ListenStarted/ListenStopped are the
 * client→server controls that delimit a speech segment (turn boundaries are
 * Phase 6's VAD; here the client marks them). While listening, the server emits
 * ASRPartial per decoded chunk and one ASRFinal on the segment commit, carrying
 * the wake-detection result + the address-stripped request body.
 */
export const TypeASRPartial = "ASRPartial";
/**
 * Phase 5 local-ASR event types. ListenStarted/ListenStopped are the
 * client→server controls that delimit a speech segment (turn boundaries are
 * Phase 6's VAD; here the client marks them). While listening, the server emits
 * ASRPartial per decoded chunk and one ASRFinal on the segment commit, carrying
 * the wake-detection result + the address-stripped request body.
 */
export const TypeASRFinal = "ASRFinal";
/**
 * Phase 6 live-voice event types. SessionUpdate is the client→server control that
 * turns the live conversation loop on/off and carries the OpenAI-shaped
 * turn_detection config (null turn_detection exits live mode); SessionUpdated is
 * the ack. Server-VAD turn boundaries are reported as SpeechStarted/SpeechStopped
 * (distinct from the manual ListenStarted/Stopped). On a confirmed barge-in the
 * server emits UserInterrupted (already defined, Phase 3) + ConversationTruncated,
 * which carries the assistant turn truncated to the last actually-played audio.
 */
export const TypeSessionUpdate = "SessionUpdate"; // client->server: enable/disable live mode + turn_detection
/**
 * Phase 6 live-voice event types. SessionUpdate is the client→server control that
 * turns the live conversation loop on/off and carries the OpenAI-shaped
 * turn_detection config (null turn_detection exits live mode); SessionUpdated is
 * the ack. Server-VAD turn boundaries are reported as SpeechStarted/SpeechStopped
 * (distinct from the manual ListenStarted/Stopped). On a confirmed barge-in the
 * server emits UserInterrupted (already defined, Phase 3) + ConversationTruncated,
 * which carries the assistant turn truncated to the last actually-played audio.
 */
export const TypeSessionUpdated = "SessionUpdated"; // server->client: live-mode ack with the active config
/**
 * Phase 6 live-voice event types. SessionUpdate is the client→server control that
 * turns the live conversation loop on/off and carries the OpenAI-shaped
 * turn_detection config (null turn_detection exits live mode); SessionUpdated is
 * the ack. Server-VAD turn boundaries are reported as SpeechStarted/SpeechStopped
 * (distinct from the manual ListenStarted/Stopped). On a confirmed barge-in the
 * server emits UserInterrupted (already defined, Phase 3) + ConversationTruncated,
 * which carries the assistant turn truncated to the last actually-played audio.
 */
export const TypeSpeechStarted = "SpeechStarted"; // server->client: VAD detected speech onset (turn opened)
/**
 * Phase 6 live-voice event types. SessionUpdate is the client→server control that
 * turns the live conversation loop on/off and carries the OpenAI-shaped
 * turn_detection config (null turn_detection exits live mode); SessionUpdated is
 * the ack. Server-VAD turn boundaries are reported as SpeechStarted/SpeechStopped
 * (distinct from the manual ListenStarted/Stopped). On a confirmed barge-in the
 * server emits UserInterrupted (already defined, Phase 3) + ConversationTruncated,
 * which carries the assistant turn truncated to the last actually-played audio.
 */
export const TypeSpeechStopped = "SpeechStopped"; // server->client: VAD committed/cancelled the turn
/**
 * Phase 6 live-voice event types. SessionUpdate is the client→server control that
 * turns the live conversation loop on/off and carries the OpenAI-shaped
 * turn_detection config (null turn_detection exits live mode); SessionUpdated is
 * the ack. Server-VAD turn boundaries are reported as SpeechStarted/SpeechStopped
 * (distinct from the manual ListenStarted/Stopped). On a confirmed barge-in the
 * server emits UserInterrupted (already defined, Phase 3) + ConversationTruncated,
 * which carries the assistant turn truncated to the last actually-played audio.
 */
export const TypeConversationTruncated = "ConversationTruncated";
/**
 * Event is the typed envelope. JSON field names are the wire contract; note
 * ConversationID serializes as "session_id" (the product-level "session").
 */
export interface Event {
  event_id: string;
  session_id?: string;
  user_id?: string;
  turn_id?: string;
  seq: number /* int64 */;
  server_ts: string;
  source: string;
  type: string;
  payload?: unknown;
}
